### ISSUE TITLE
Testing error

### ISSUE THREAD

**Issue by oplummer-sysomos** [angular/benchpress-tree#10]
After following the instructions and trying to run the provided protractor test, i get the following error:

Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver
[launcher] Error: SyntaxError: Unexpected token )
    at goog.loadModuleFromSource_ (/Users/oplummer/Documents/projects/benchpress-guild2/benchpress-tree/node_modules/benchpress/node_modules/selenium-webdriver/lib/goog/base.js:1123:19)
    at Object.goog.loadModule (/Users/oplummer/Documents/projects/benchpress-guild2/benchpress-tree/node_modules/benchpress/node_modules/selenium-webdriver/lib/goog/base.js:1085:46)
    at /Users/oplummer/Documents/projects/benchpress-guild2/benchpress-tree/node_modules/benchpress/node_modules/selenium-webdriver/lib/webdriver/promise.js:1:6
    at Object.exports.runInContext (vm.js:44:17)
    at Object.Context.closure.goog.retrieveAndExecModule_ (/Users/oplummer/Documents/projects/benchpress-guild2/benchpress-tree/node_modules/benchpress/node_modules/selenium-webdriver/_base.js:135:8)
    at <anonymous>:1:6
    at Object.exports.runInContext (vm.js:44:17)
    at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (/Users/oplummer/Documents/projects/benchpress-guild2/benchpress-tree/node_modules/benchpress/node_modules/selenium-webdriver/_base.js:104:12)
    at Object.goog.importScript_ (/Users/oplummer/Documents/projects/benchpress-guild2/benchpress-tree/node_modules/benchpress/node_modules/selenium-webdriver/lib/goog/base.js:879:9)
    at Object.goog.importModule_ (/Users/oplummer/Documents/projects/benchpress-guild2/benchpress-tree/node_modules/benchpress/node_modules/selenium-webdriver/lib/goog/base.js:900:14)
[launcher] Process exited with error code 100

**Comment by cssensei** [comment]
Same error for me :(

**Comment by cssensei** [comment]
This can be easily fixed by upgrading node version.
