### ISSUE TITLE
Error: Tried too often to get the ending mark: 21

### ISSUE THREAD

**Issue by mittalnarain123** [angular/benchpress-tree#14]
I get this error when I try to run ./node_modules/.bin/protractor protractor.conf.js after a successful npm install . and ./node_modules/.bin/webdriver-manager update

`
[11:54:36] E/launcher - Tried too often to get the ending mark: 21
[11:54:36] E/launcher - Error: Tried too often to get the ending mark: 21
    at PerflogMetric._readUntilEndMark (C:\Users\tbosch\projects\angular\modules\@angular\benchpress\src\metric\perflog_metric.ts:150:13)
    at Timeout._onTimeout (C:\Users\tbosch\projects\angular\modules\@angular\benchpress\src\metric\perflog_metric.ts:161:43)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[11:54:36] E/launcher - Process exited with error code 199
`
full trace:

$ ./node_modules/.bin/protractor protractor.conf.js
[11:54:27] I/direct - Using ChromeDriver directly...
[11:54:27] I/launcher - Running 1 instances of WebDriver
Started
*BENCHMARK deep-tree
Description:
- depth: 11
- forceGc: true
- regressionSlopeMetric: scriptTime
- sampleSize: 10
- userAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Metrics:
- forcedGcAmount: forced gc amount in kbytes
- forcedGcTime: forced gc time in ms
- gcAmount: gc amount in kbytes
- gcTime: gc time in ms
- majorGcTime: time of major gcs in ms
- pureScriptTime: script execution time in ms, without gc nor render
- renderTime: render time in ms
- scriptTime: script execution time in ms, including gc and render

    forcedGcAmount |       forcedGcTime |           gcAmount |             gcTime |        majorGcTime |     pureScriptTime |         renderTime |         scriptTime
------------------ | ------------------ | ------------------ | ------------------ | ------------------ | ------------------ | ------------------ | ------------------
[11:54:36] E/launcher - Tried too often to get the ending mark: 21
[11:54:36] E/launcher - Error: Tried too often to get the ending mark: 21
    at PerflogMetric._readUntilEndMark (C:\Users\tbosch\projects\angular\modules\@angular\benchpress\src\metric\perflog_metric.ts:150:13)
    at Timeout._onTimeout (C:\Users\tbosch\projects\angular\modules\@angular\benchpress\src\metric\perflog_metric.ts:161:43)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[11:54:36] E/launcher - Process exited with error code 199

**Comment by pawelczak** [comment]
Same problem. Does anyone found a solution?
