### ISSUE TITLE
TypeError: Object [object Object] has no method 'serialize' when running protractor

### ISSUE THREAD

**Issue by almilo** [angular/benchpress-tree#9]
Following the instructions to install and run the project, I get:

Message:
    Failed: TypeError: Object [object Object] has no method 'serialize'
  Stack:
    Error: Failed: TypeError: Object [object Object] has no method 'serialize'
        at /Java/edorasware/test/benchpress-tree/node_modules/protractor/node_modules/jasminewd2/index.js:104:16
        at /Java/edorasware/test/benchpress-tree/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
        at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/Java/edorasware/test/benchpress-tree/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
        at notify (/Java/edorasware/test/benchpress-tree/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)

Any idea where could the issue?
Thanks!!

**Comment by EliSnow** [comment]
I am receiving this same error.
